# Generated by Django 4.1.3 on 2022-12-04 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(upload_to='Обложки курсов/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость курса')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='EducationalMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('file', models.FileField(upload_to='Файлы урока/%Y/%m/%d')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course.course', verbose_name='Материалы курса')),
            ],
            options={
                'verbose_name': 'Материал курса',
                'verbose_name_plural': 'Материалы курса',
            },
        ),
        migrations.CreateModel(
            name='CourseStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='course.course', verbose_name='Курс')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Студента курса',
                'verbose_name_plural': 'Студенты курса',
            },
        ),
    ]
