# Generated by Django 4.1.3 on 2022-12-04 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='ФИО')),
                ('phone_number', models.CharField(default='+996', max_length=15, null=True, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[('python', 'Python'), ('js', 'JavaScript')], max_length=50, null=True, verbose_name='Направление')),
                ('is_staff', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(default='+996', max_length=15, verbose_name='Номер телефона')),
                ('enrolled', models.BooleanField(default=False, verbose_name='Записан')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=50, verbose_name='Время обучения')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_date', models.DateTimeField(auto_now=True, verbose_name='Дата поступления')),
                ('rate', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('standart+', 'Standart+')], max_length=20, verbose_name='Тариф')),
                ('payment', models.IntegerField(verbose_name='Оплата')),
                ('remaining_amount', models.IntegerField(default=15000, verbose_name='Остаток')),
                ('end_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата окончания')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='Сетификаты/%Y/%m/%d', verbose_name='Сертификат')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата:')),
                ('subject', models.CharField(max_length=50, verbose_name='Тема:')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
                ('oop', models.CharField(max_length=50, verbose_name='OOP')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='accounts.student', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
